/*
 * Decompiled with CFR 0.152.
 */
package org.mapleir.dot4j.attr.builtin;

import org.mapleir.dot4j.attr.Attr;
import org.mapleir.dot4j.attr.Attrs;
import org.mapleir.dot4j.attr.builtin.Style;

public class Colour
extends Attr<String> {
    public static final Colour ALICEBLUE = Colour.named("aliceblue");
    public static final Colour ANTIQUEWHITE = Colour.named("antiquewhite");
    public static final Colour ANTIQUEWHITE1 = Colour.named("antiquewhite1");
    public static final Colour ANTIQUEWHITE2 = Colour.named("antiquewhite2");
    public static final Colour ANTIQUEWHITE3 = Colour.named("antiquewhite3");
    public static final Colour ANTIQUEWHITE4 = Colour.named("antiquewhite4");
    public static final Colour AQUAMARINE = Colour.named("aquamarine");
    public static final Colour AQUAMARINE1 = Colour.named("aquamarine1");
    public static final Colour AQUAMARINE2 = Colour.named("aquamarine2");
    public static final Colour AQUAMARINE3 = Colour.named("aquamarine3");
    public static final Colour AQUAMARINE4 = Colour.named("aquamarine4");
    public static final Colour AZURE = Colour.named("azure");
    public static final Colour AZURE1 = Colour.named("azure1");
    public static final Colour AZURE2 = Colour.named("azure2");
    public static final Colour AZURE3 = Colour.named("azure3");
    public static final Colour AZURE4 = Colour.named("azure4");
    public static final Colour BEIGE = Colour.named("beige");
    public static final Colour BISQUE = Colour.named("bisque");
    public static final Colour BISQUE1 = Colour.named("bisque1");
    public static final Colour BISQUE2 = Colour.named("bisque2");
    public static final Colour BISQUE3 = Colour.named("bisque3");
    public static final Colour BISQUE4 = Colour.named("bisque4");
    public static final Colour BLACK = Colour.named("black");
    public static final Colour BLANCHEDALMOND = Colour.named("blanchedalmond");
    public static final Colour BLUE = Colour.named("blue");
    public static final Colour BLUE1 = Colour.named("blue1");
    public static final Colour BLUE2 = Colour.named("blue2");
    public static final Colour BLUE3 = Colour.named("blue3");
    public static final Colour BLUE4 = Colour.named("blue4");
    public static final Colour BLUEVIOLET = Colour.named("blueviolet");
    public static final Colour BROWN = Colour.named("brown");
    public static final Colour BROWN1 = Colour.named("brown1");
    public static final Colour BROWN2 = Colour.named("brown2");
    public static final Colour BROWN3 = Colour.named("brown3");
    public static final Colour BROWN4 = Colour.named("brown4");
    public static final Colour BURLYWOOD = Colour.named("burlywood");
    public static final Colour BURLYWOOD1 = Colour.named("burlywood1");
    public static final Colour BURLYWOOD2 = Colour.named("burlywood2");
    public static final Colour BURLYWOOD3 = Colour.named("burlywood3");
    public static final Colour BURLYWOOD4 = Colour.named("burlywood4");
    public static final Colour CADETBLUE = Colour.named("cadetblue");
    public static final Colour CADETBLUE1 = Colour.named("cadetblue1");
    public static final Colour CADETBLUE2 = Colour.named("cadetblue2");
    public static final Colour CADETBLUE3 = Colour.named("cadetblue3");
    public static final Colour CADETBLUE4 = Colour.named("cadetblue4");
    public static final Colour CHARTREUSE = Colour.named("chartreuse");
    public static final Colour CHARTREUSE1 = Colour.named("chartreuse1");
    public static final Colour CHARTREUSE2 = Colour.named("chartreuse2");
    public static final Colour CHARTREUSE3 = Colour.named("chartreuse3");
    public static final Colour CHARTREUSE4 = Colour.named("chartreuse4");
    public static final Colour CHOCOLATE = Colour.named("chocolate");
    public static final Colour CHOCOLATE1 = Colour.named("chocolate1");
    public static final Colour CHOCOLATE2 = Colour.named("chocolate2");
    public static final Colour CHOCOLATE3 = Colour.named("chocolate3");
    public static final Colour CHOCOLATE4 = Colour.named("chocolate4");
    public static final Colour CORAL = Colour.named("coral");
    public static final Colour CORAL1 = Colour.named("coral1");
    public static final Colour CORAL2 = Colour.named("coral2");
    public static final Colour CORAL3 = Colour.named("coral3");
    public static final Colour CORAL4 = Colour.named("coral4");
    public static final Colour CORNFLOWERBLUE = Colour.named("cornflowerblue");
    public static final Colour CORNSILK = Colour.named("cornsilk");
    public static final Colour CORNSILK1 = Colour.named("cornsilk1");
    public static final Colour CORNSILK2 = Colour.named("cornsilk2");
    public static final Colour CORNSILK3 = Colour.named("cornsilk3");
    public static final Colour CORNSILK4 = Colour.named("cornsilk4");
    public static final Colour CRIMSON = Colour.named("crimson");
    public static final Colour CYAN = Colour.named("cyan");
    public static final Colour CYAN1 = Colour.named("cyan1");
    public static final Colour CYAN2 = Colour.named("cyan2");
    public static final Colour CYAN3 = Colour.named("cyan3");
    public static final Colour CYAN4 = Colour.named("cyan4");
    public static final Colour DARKGOLDENROD = Colour.named("darkgoldenrod");
    public static final Colour DARKGOLDENROD1 = Colour.named("darkgoldenrod1");
    public static final Colour DARKGOLDENROD2 = Colour.named("darkgoldenrod2");
    public static final Colour DARKGOLDENROD3 = Colour.named("darkgoldenrod3");
    public static final Colour DARKGOLDENROD4 = Colour.named("darkgoldenrod4");
    public static final Colour DARKGREEN = Colour.named("darkgreen");
    public static final Colour DARKKHAKI = Colour.named("darkkhaki");
    public static final Colour DARKOLIVEGREEN = Colour.named("darkolivegreen");
    public static final Colour DARKOLIVEGREEN1 = Colour.named("darkolivegreen1");
    public static final Colour DARKOLIVEGREEN2 = Colour.named("darkolivegreen2");
    public static final Colour DARKOLIVEGREEN3 = Colour.named("darkolivegreen3");
    public static final Colour DARKOLIVEGREEN4 = Colour.named("darkolivegreen4");
    public static final Colour DARKORANGE = Colour.named("darkorange");
    public static final Colour DARKORANGE1 = Colour.named("darkorange1");
    public static final Colour DARKORANGE2 = Colour.named("darkorange2");
    public static final Colour DARKORANGE3 = Colour.named("darkorange3");
    public static final Colour DARKORANGE4 = Colour.named("darkorange4");
    public static final Colour DARKORCHID = Colour.named("darkorchid");
    public static final Colour DARKORCHID1 = Colour.named("darkorchid1");
    public static final Colour DARKORCHID2 = Colour.named("darkorchid2");
    public static final Colour DARKORCHID3 = Colour.named("darkorchid3");
    public static final Colour DARKORCHID4 = Colour.named("darkorchid4");
    public static final Colour DARKSALMON = Colour.named("darksalmon");
    public static final Colour DARKSEAGREEN = Colour.named("darkseagreen");
    public static final Colour DARKSEAGREEN1 = Colour.named("darkseagreen1");
    public static final Colour DARKSEAGREEN2 = Colour.named("darkseagreen2");
    public static final Colour DARKSEAGREEN3 = Colour.named("darkseagreen3");
    public static final Colour DARKSEAGREEN4 = Colour.named("darkseagreen4");
    public static final Colour DARKSLATEBLUE = Colour.named("darkslateblue");
    public static final Colour DARKSLATEGRAY = Colour.named("darkslategray");
    public static final Colour DARKSLATEGRAY1 = Colour.named("darkslategray1");
    public static final Colour DARKSLATEGRAY2 = Colour.named("darkslategray2");
    public static final Colour DARKSLATEGRAY3 = Colour.named("darkslategray3");
    public static final Colour DARKSLATEGRAY4 = Colour.named("darkslategray4");
    public static final Colour DARKSLATEGREY = Colour.named("darkslategrey");
    public static final Colour DARKTURQUOISE = Colour.named("darkturquoise");
    public static final Colour DARKVIOLET = Colour.named("darkviolet");
    public static final Colour DEEPPINK = Colour.named("deeppink");
    public static final Colour DEEPPINK1 = Colour.named("deeppink1");
    public static final Colour DEEPPINK2 = Colour.named("deeppink2");
    public static final Colour DEEPPINK3 = Colour.named("deeppink3");
    public static final Colour DEEPPINK4 = Colour.named("deeppink4");
    public static final Colour DEEPSKYBLUE = Colour.named("deepskyblue");
    public static final Colour DEEPSKYBLUE1 = Colour.named("deepskyblue1");
    public static final Colour DEEPSKYBLUE2 = Colour.named("deepskyblue2");
    public static final Colour DEEPSKYBLUE3 = Colour.named("deepskyblue3");
    public static final Colour DEEPSKYBLUE4 = Colour.named("deepskyblue4");
    public static final Colour DIMGRAY = Colour.named("dimgray");
    public static final Colour DIMGREY = Colour.named("dimgrey");
    public static final Colour DODGERBLUE = Colour.named("dodgerblue");
    public static final Colour DODGERBLUE1 = Colour.named("dodgerblue1");
    public static final Colour DODGERBLUE2 = Colour.named("dodgerblue2");
    public static final Colour DODGERBLUE3 = Colour.named("dodgerblue3");
    public static final Colour DODGERBLUE4 = Colour.named("dodgerblue4");
    public static final Colour FIREBRICK = Colour.named("firebrick");
    public static final Colour FIREBRICK1 = Colour.named("firebrick1");
    public static final Colour FIREBRICK2 = Colour.named("firebrick2");
    public static final Colour FIREBRICK3 = Colour.named("firebrick3");
    public static final Colour FIREBRICK4 = Colour.named("firebrick4");
    public static final Colour FLORALWHITE = Colour.named("floralwhite");
    public static final Colour FORESTGREEN = Colour.named("forestgreen");
    public static final Colour GAINSBORO = Colour.named("gainsboro");
    public static final Colour GHOSTWHITE = Colour.named("ghostwhite");
    public static final Colour GOLD = Colour.named("gold");
    public static final Colour GOLD1 = Colour.named("gold1");
    public static final Colour GOLD2 = Colour.named("gold2");
    public static final Colour GOLD3 = Colour.named("gold3");
    public static final Colour GOLD4 = Colour.named("gold4");
    public static final Colour GOLDENROD = Colour.named("goldenrod");
    public static final Colour GOLDENROD1 = Colour.named("goldenrod1");
    public static final Colour GOLDENROD2 = Colour.named("goldenrod2");
    public static final Colour GOLDENROD3 = Colour.named("goldenrod3");
    public static final Colour GOLDENROD4 = Colour.named("goldenrod4");
    public static final Colour GRAY = Colour.named("gray");
    public static final Colour GRAY0 = Colour.named("gray0");
    public static final Colour GRAY1 = Colour.named("gray1");
    public static final Colour GRAY10 = Colour.named("gray10");
    public static final Colour GRAY100 = Colour.named("gray100");
    public static final Colour GRAY11 = Colour.named("gray11");
    public static final Colour GRAY12 = Colour.named("gray12");
    public static final Colour GRAY13 = Colour.named("gray13");
    public static final Colour GRAY14 = Colour.named("gray14");
    public static final Colour GRAY15 = Colour.named("gray15");
    public static final Colour GRAY16 = Colour.named("gray16");
    public static final Colour GRAY17 = Colour.named("gray17");
    public static final Colour GRAY18 = Colour.named("gray18");
    public static final Colour GRAY19 = Colour.named("gray19");
    public static final Colour GRAY2 = Colour.named("gray2");
    public static final Colour GRAY20 = Colour.named("gray20");
    public static final Colour GRAY21 = Colour.named("gray21");
    public static final Colour GRAY22 = Colour.named("gray22");
    public static final Colour GRAY23 = Colour.named("gray23");
    public static final Colour GRAY24 = Colour.named("gray24");
    public static final Colour GRAY25 = Colour.named("gray25");
    public static final Colour GRAY26 = Colour.named("gray26");
    public static final Colour GRAY27 = Colour.named("gray27");
    public static final Colour GRAY28 = Colour.named("gray28");
    public static final Colour GRAY29 = Colour.named("gray29");
    public static final Colour GRAY3 = Colour.named("gray3");
    public static final Colour GRAY30 = Colour.named("gray30");
    public static final Colour GRAY31 = Colour.named("gray31");
    public static final Colour GRAY32 = Colour.named("gray32");
    public static final Colour GRAY33 = Colour.named("gray33");
    public static final Colour GRAY34 = Colour.named("gray34");
    public static final Colour GRAY35 = Colour.named("gray35");
    public static final Colour GRAY36 = Colour.named("gray36");
    public static final Colour GRAY37 = Colour.named("gray37");
    public static final Colour GRAY38 = Colour.named("gray38");
    public static final Colour GRAY39 = Colour.named("gray39");
    public static final Colour GRAY4 = Colour.named("gray4");
    public static final Colour GRAY40 = Colour.named("gray40");
    public static final Colour GRAY41 = Colour.named("gray41");
    public static final Colour GRAY42 = Colour.named("gray42");
    public static final Colour GRAY43 = Colour.named("gray43");
    public static final Colour GRAY44 = Colour.named("gray44");
    public static final Colour GRAY45 = Colour.named("gray45");
    public static final Colour GRAY46 = Colour.named("gray46");
    public static final Colour GRAY47 = Colour.named("gray47");
    public static final Colour GRAY48 = Colour.named("gray48");
    public static final Colour GRAY49 = Colour.named("gray49");
    public static final Colour GRAY5 = Colour.named("gray5");
    public static final Colour GRAY50 = Colour.named("gray50");
    public static final Colour GRAY51 = Colour.named("gray51");
    public static final Colour GRAY52 = Colour.named("gray52");
    public static final Colour GRAY53 = Colour.named("gray53");
    public static final Colour GRAY54 = Colour.named("gray54");
    public static final Colour GRAY55 = Colour.named("gray55");
    public static final Colour GRAY56 = Colour.named("gray56");
    public static final Colour GRAY57 = Colour.named("gray57");
    public static final Colour GRAY58 = Colour.named("gray58");
    public static final Colour GRAY59 = Colour.named("gray59");
    public static final Colour GRAY6 = Colour.named("gray6");
    public static final Colour GRAY60 = Colour.named("gray60");
    public static final Colour GRAY61 = Colour.named("gray61");
    public static final Colour GRAY62 = Colour.named("gray62");
    public static final Colour GRAY63 = Colour.named("gray63");
    public static final Colour GRAY64 = Colour.named("gray64");
    public static final Colour GRAY65 = Colour.named("gray65");
    public static final Colour GRAY66 = Colour.named("gray66");
    public static final Colour GRAY67 = Colour.named("gray67");
    public static final Colour GRAY68 = Colour.named("gray68");
    public static final Colour GRAY69 = Colour.named("gray69");
    public static final Colour GRAY7 = Colour.named("gray7");
    public static final Colour GRAY70 = Colour.named("gray70");
    public static final Colour GRAY71 = Colour.named("gray71");
    public static final Colour GRAY72 = Colour.named("gray72");
    public static final Colour GRAY73 = Colour.named("gray73");
    public static final Colour GRAY74 = Colour.named("gray74");
    public static final Colour GRAY75 = Colour.named("gray75");
    public static final Colour GRAY76 = Colour.named("gray76");
    public static final Colour GRAY77 = Colour.named("gray77");
    public static final Colour GRAY78 = Colour.named("gray78");
    public static final Colour GRAY79 = Colour.named("gray79");
    public static final Colour GRAY8 = Colour.named("gray8");
    public static final Colour GRAY80 = Colour.named("gray80");
    public static final Colour GRAY81 = Colour.named("gray81");
    public static final Colour GRAY82 = Colour.named("gray82");
    public static final Colour GRAY83 = Colour.named("gray83");
    public static final Colour GRAY84 = Colour.named("gray84");
    public static final Colour GRAY85 = Colour.named("gray85");
    public static final Colour GRAY86 = Colour.named("gray86");
    public static final Colour GRAY87 = Colour.named("gray87");
    public static final Colour GRAY88 = Colour.named("gray88");
    public static final Colour GRAY89 = Colour.named("gray89");
    public static final Colour GRAY9 = Colour.named("gray9");
    public static final Colour GRAY90 = Colour.named("gray90");
    public static final Colour GRAY91 = Colour.named("gray91");
    public static final Colour GRAY92 = Colour.named("gray92");
    public static final Colour GRAY93 = Colour.named("gray93");
    public static final Colour GRAY94 = Colour.named("gray94");
    public static final Colour GRAY95 = Colour.named("gray95");
    public static final Colour GRAY96 = Colour.named("gray96");
    public static final Colour GRAY97 = Colour.named("gray97");
    public static final Colour GRAY98 = Colour.named("gray98");
    public static final Colour GRAY99 = Colour.named("gray99");
    public static final Colour GREEN = Colour.named("green");
    public static final Colour GREEN1 = Colour.named("green1");
    public static final Colour GREEN2 = Colour.named("green2");
    public static final Colour GREEN3 = Colour.named("green3");
    public static final Colour GREEN4 = Colour.named("green4");
    public static final Colour GREENYELLOW = Colour.named("greenyellow");
    public static final Colour GREY = Colour.named("grey");
    public static final Colour GREY0 = Colour.named("grey0");
    public static final Colour GREY1 = Colour.named("grey1");
    public static final Colour GREY10 = Colour.named("grey10");
    public static final Colour GREY100 = Colour.named("grey100");
    public static final Colour GREY11 = Colour.named("grey11");
    public static final Colour GREY12 = Colour.named("grey12");
    public static final Colour GREY13 = Colour.named("grey13");
    public static final Colour GREY14 = Colour.named("grey14");
    public static final Colour GREY15 = Colour.named("grey15");
    public static final Colour GREY16 = Colour.named("grey16");
    public static final Colour GREY17 = Colour.named("grey17");
    public static final Colour GREY18 = Colour.named("grey18");
    public static final Colour GREY19 = Colour.named("grey19");
    public static final Colour GREY2 = Colour.named("grey2");
    public static final Colour GREY20 = Colour.named("grey20");
    public static final Colour GREY21 = Colour.named("grey21");
    public static final Colour GREY22 = Colour.named("grey22");
    public static final Colour GREY23 = Colour.named("grey23");
    public static final Colour GREY24 = Colour.named("grey24");
    public static final Colour GREY25 = Colour.named("grey25");
    public static final Colour GREY26 = Colour.named("grey26");
    public static final Colour GREY27 = Colour.named("grey27");
    public static final Colour GREY28 = Colour.named("grey28");
    public static final Colour GREY29 = Colour.named("grey29");
    public static final Colour GREY3 = Colour.named("grey3");
    public static final Colour GREY30 = Colour.named("grey30");
    public static final Colour GREY31 = Colour.named("grey31");
    public static final Colour GREY32 = Colour.named("grey32");
    public static final Colour GREY33 = Colour.named("grey33");
    public static final Colour GREY34 = Colour.named("grey34");
    public static final Colour GREY35 = Colour.named("grey35");
    public static final Colour GREY36 = Colour.named("grey36");
    public static final Colour GREY37 = Colour.named("grey37");
    public static final Colour GREY38 = Colour.named("grey38");
    public static final Colour GREY39 = Colour.named("grey39");
    public static final Colour GREY4 = Colour.named("grey4");
    public static final Colour GREY40 = Colour.named("grey40");
    public static final Colour GREY41 = Colour.named("grey41");
    public static final Colour GREY42 = Colour.named("grey42");
    public static final Colour GREY43 = Colour.named("grey43");
    public static final Colour GREY44 = Colour.named("grey44");
    public static final Colour GREY45 = Colour.named("grey45");
    public static final Colour GREY46 = Colour.named("grey46");
    public static final Colour GREY47 = Colour.named("grey47");
    public static final Colour GREY48 = Colour.named("grey48");
    public static final Colour GREY49 = Colour.named("grey49");
    public static final Colour GREY5 = Colour.named("grey5");
    public static final Colour GREY50 = Colour.named("grey50");
    public static final Colour GREY51 = Colour.named("grey51");
    public static final Colour GREY52 = Colour.named("grey52");
    public static final Colour GREY53 = Colour.named("grey53");
    public static final Colour GREY54 = Colour.named("grey54");
    public static final Colour GREY55 = Colour.named("grey55");
    public static final Colour GREY56 = Colour.named("grey56");
    public static final Colour GREY57 = Colour.named("grey57");
    public static final Colour GREY58 = Colour.named("grey58");
    public static final Colour GREY59 = Colour.named("grey59");
    public static final Colour GREY6 = Colour.named("grey6");
    public static final Colour GREY60 = Colour.named("grey60");
    public static final Colour GREY61 = Colour.named("grey61");
    public static final Colour GREY62 = Colour.named("grey62");
    public static final Colour GREY63 = Colour.named("grey63");
    public static final Colour GREY64 = Colour.named("grey64");
    public static final Colour GREY65 = Colour.named("grey65");
    public static final Colour GREY66 = Colour.named("grey66");
    public static final Colour GREY67 = Colour.named("grey67");
    public static final Colour GREY68 = Colour.named("grey68");
    public static final Colour GREY69 = Colour.named("grey69");
    public static final Colour GREY7 = Colour.named("grey7");
    public static final Colour GREY70 = Colour.named("grey70");
    public static final Colour GREY71 = Colour.named("grey71");
    public static final Colour GREY72 = Colour.named("grey72");
    public static final Colour GREY73 = Colour.named("grey73");
    public static final Colour GREY74 = Colour.named("grey74");
    public static final Colour GREY75 = Colour.named("grey75");
    public static final Colour GREY76 = Colour.named("grey76");
    public static final Colour GREY77 = Colour.named("grey77");
    public static final Colour GREY78 = Colour.named("grey78");
    public static final Colour GREY79 = Colour.named("grey79");
    public static final Colour GREY8 = Colour.named("grey8");
    public static final Colour GREY80 = Colour.named("grey80");
    public static final Colour GREY81 = Colour.named("grey81");
    public static final Colour GREY82 = Colour.named("grey82");
    public static final Colour GREY83 = Colour.named("grey83");
    public static final Colour GREY84 = Colour.named("grey84");
    public static final Colour GREY85 = Colour.named("grey85");
    public static final Colour GREY86 = Colour.named("grey86");
    public static final Colour GREY87 = Colour.named("grey87");
    public static final Colour GREY88 = Colour.named("grey88");
    public static final Colour GREY89 = Colour.named("grey89");
    public static final Colour GREY9 = Colour.named("grey9");
    public static final Colour GREY90 = Colour.named("grey90");
    public static final Colour GREY91 = Colour.named("grey91");
    public static final Colour GREY92 = Colour.named("grey92");
    public static final Colour GREY93 = Colour.named("grey93");
    public static final Colour GREY94 = Colour.named("grey94");
    public static final Colour GREY95 = Colour.named("grey95");
    public static final Colour GREY96 = Colour.named("grey96");
    public static final Colour GREY97 = Colour.named("grey97");
    public static final Colour GREY98 = Colour.named("grey98");
    public static final Colour GREY99 = Colour.named("grey99");
    public static final Colour HONEYDEW = Colour.named("honeydew");
    public static final Colour HONEYDEW1 = Colour.named("honeydew1");
    public static final Colour HONEYDEW2 = Colour.named("honeydew2");
    public static final Colour HONEYDEW3 = Colour.named("honeydew3");
    public static final Colour HONEYDEW4 = Colour.named("honeydew4");
    public static final Colour HOTPINK = Colour.named("hotpink");
    public static final Colour HOTPINK1 = Colour.named("hotpink1");
    public static final Colour HOTPINK2 = Colour.named("hotpink2");
    public static final Colour HOTPINK3 = Colour.named("hotpink3");
    public static final Colour HOTPINK4 = Colour.named("hotpink4");
    public static final Colour INDIANRED = Colour.named("indianred");
    public static final Colour INDIANRED1 = Colour.named("indianred1");
    public static final Colour INDIANRED2 = Colour.named("indianred2");
    public static final Colour INDIANRED3 = Colour.named("indianred3");
    public static final Colour INDIANRED4 = Colour.named("indianred4");
    public static final Colour INDIGO = Colour.named("indigo");
    public static final Colour IVORY = Colour.named("ivory");
    public static final Colour IVORY1 = Colour.named("ivory1");
    public static final Colour IVORY2 = Colour.named("ivory2");
    public static final Colour IVORY3 = Colour.named("ivory3");
    public static final Colour IVORY4 = Colour.named("ivory4");
    public static final Colour KHAKI = Colour.named("khaki");
    public static final Colour KHAKI1 = Colour.named("khaki1");
    public static final Colour KHAKI2 = Colour.named("khaki2");
    public static final Colour KHAKI3 = Colour.named("khaki3");
    public static final Colour KHAKI4 = Colour.named("khaki4");
    public static final Colour LAVENDER = Colour.named("lavender");
    public static final Colour LAVENDERBLUSH = Colour.named("lavenderblush");
    public static final Colour LAVENDERBLUSH1 = Colour.named("lavenderblush1");
    public static final Colour LAVENDERBLUSH2 = Colour.named("lavenderblush2");
    public static final Colour LAVENDERBLUSH3 = Colour.named("lavenderblush3");
    public static final Colour LAVENDERBLUSH4 = Colour.named("lavenderblush4");
    public static final Colour LAWNGREEN = Colour.named("lawngreen");
    public static final Colour LEMONCHIFFON = Colour.named("lemonchiffon");
    public static final Colour LEMONCHIFFON1 = Colour.named("lemonchiffon1");
    public static final Colour LEMONCHIFFON2 = Colour.named("lemonchiffon2");
    public static final Colour LEMONCHIFFON3 = Colour.named("lemonchiffon3");
    public static final Colour LEMONCHIFFON4 = Colour.named("lemonchiffon4");
    public static final Colour LIGHTBLUE = Colour.named("lightblue");
    public static final Colour LIGHTBLUE1 = Colour.named("lightblue1");
    public static final Colour LIGHTBLUE2 = Colour.named("lightblue2");
    public static final Colour LIGHTBLUE3 = Colour.named("lightblue3");
    public static final Colour LIGHTBLUE4 = Colour.named("lightblue4");
    public static final Colour LIGHTCORAL = Colour.named("lightcoral");
    public static final Colour LIGHTCYAN = Colour.named("lightcyan");
    public static final Colour LIGHTCYAN1 = Colour.named("lightcyan1");
    public static final Colour LIGHTCYAN2 = Colour.named("lightcyan2");
    public static final Colour LIGHTCYAN3 = Colour.named("lightcyan3");
    public static final Colour LIGHTCYAN4 = Colour.named("lightcyan4");
    public static final Colour LIGHTGOLDENROD = Colour.named("lightgoldenrod");
    public static final Colour LIGHTGOLDENROD1 = Colour.named("lightgoldenrod1");
    public static final Colour LIGHTGOLDENROD2 = Colour.named("lightgoldenrod2");
    public static final Colour LIGHTGOLDENROD3 = Colour.named("lightgoldenrod3");
    public static final Colour LIGHTGOLDENROD4 = Colour.named("lightgoldenrod4");
    public static final Colour LIGHTGOLDENRODYELLOW = Colour.named("lightgoldenrodyellow");
    public static final Colour LIGHTGRAY = Colour.named("lightgray");
    public static final Colour LIGHTGREY = Colour.named("lightgrey");
    public static final Colour LIGHTPINK = Colour.named("lightpink");
    public static final Colour LIGHTPINK1 = Colour.named("lightpink1");
    public static final Colour LIGHTPINK2 = Colour.named("lightpink2");
    public static final Colour LIGHTPINK3 = Colour.named("lightpink3");
    public static final Colour LIGHTPINK4 = Colour.named("lightpink4");
    public static final Colour LIGHTSALMON = Colour.named("lightsalmon");
    public static final Colour LIGHTSALMON1 = Colour.named("lightsalmon1");
    public static final Colour LIGHTSALMON2 = Colour.named("lightsalmon2");
    public static final Colour LIGHTSALMON3 = Colour.named("lightsalmon3");
    public static final Colour LIGHTSALMON4 = Colour.named("lightsalmon4");
    public static final Colour LIGHTSEAGREEN = Colour.named("lightseagreen");
    public static final Colour LIGHTSKYBLUE = Colour.named("lightskyblue");
    public static final Colour LIGHTSKYBLUE1 = Colour.named("lightskyblue1");
    public static final Colour LIGHTSKYBLUE2 = Colour.named("lightskyblue2");
    public static final Colour LIGHTSKYBLUE3 = Colour.named("lightskyblue3");
    public static final Colour LIGHTSKYBLUE4 = Colour.named("lightskyblue4");
    public static final Colour LIGHTSLATEBLUE = Colour.named("lightslateblue");
    public static final Colour LIGHTSLATEGRAY = Colour.named("lightslategray");
    public static final Colour LIGHTSLATEGREY = Colour.named("lightslategrey");
    public static final Colour LIGHTSTEELBLUE = Colour.named("lightsteelblue");
    public static final Colour LIGHTSTEELBLUE1 = Colour.named("lightsteelblue1");
    public static final Colour LIGHTSTEELBLUE2 = Colour.named("lightsteelblue2");
    public static final Colour LIGHTSTEELBLUE3 = Colour.named("lightsteelblue3");
    public static final Colour LIGHTSTEELBLUE4 = Colour.named("lightsteelblue4");
    public static final Colour LIGHTYELLOW = Colour.named("lightyellow");
    public static final Colour LIGHTYELLOW1 = Colour.named("lightyellow1");
    public static final Colour LIGHTYELLOW2 = Colour.named("lightyellow2");
    public static final Colour LIGHTYELLOW3 = Colour.named("lightyellow3");
    public static final Colour LIGHTYELLOW4 = Colour.named("lightyellow4");
    public static final Colour LIMEGREEN = Colour.named("limegreen");
    public static final Colour LINEN = Colour.named("linen");
    public static final Colour MAGENTA = Colour.named("magenta");
    public static final Colour MAGENTA1 = Colour.named("magenta1");
    public static final Colour MAGENTA2 = Colour.named("magenta2");
    public static final Colour MAGENTA3 = Colour.named("magenta3");
    public static final Colour MAGENTA4 = Colour.named("magenta4");
    public static final Colour MAROON = Colour.named("maroon");
    public static final Colour MAROON1 = Colour.named("maroon1");
    public static final Colour MAROON2 = Colour.named("maroon2");
    public static final Colour MAROON3 = Colour.named("maroon3");
    public static final Colour MAROON4 = Colour.named("maroon4");
    public static final Colour MEDIUMAQUAMARINE = Colour.named("mediumaquamarine");
    public static final Colour MEDIUMBLUE = Colour.named("mediumblue");
    public static final Colour MEDIUMORCHID = Colour.named("mediumorchid");
    public static final Colour MEDIUMORCHID1 = Colour.named("mediumorchid1");
    public static final Colour MEDIUMORCHID2 = Colour.named("mediumorchid2");
    public static final Colour MEDIUMORCHID3 = Colour.named("mediumorchid3");
    public static final Colour MEDIUMORCHID4 = Colour.named("mediumorchid4");
    public static final Colour MEDIUMPURPLE = Colour.named("mediumpurple");
    public static final Colour MEDIUMPURPLE1 = Colour.named("mediumpurple1");
    public static final Colour MEDIUMPURPLE2 = Colour.named("mediumpurple2");
    public static final Colour MEDIUMPURPLE3 = Colour.named("mediumpurple3");
    public static final Colour MEDIUMPURPLE4 = Colour.named("mediumpurple4");
    public static final Colour MEDIUMSEAGREEN = Colour.named("mediumseagreen");
    public static final Colour MEDIUMSLATEBLUE = Colour.named("mediumslateblue");
    public static final Colour MEDIUMSPRINGGREEN = Colour.named("mediumspringgreen");
    public static final Colour MEDIUMTURQUOISE = Colour.named("mediumturquoise");
    public static final Colour MEDIUMVIOLETRED = Colour.named("mediumvioletred");
    public static final Colour MIDNIGHTBLUE = Colour.named("midnightblue");
    public static final Colour MINTCREAM = Colour.named("mintcream");
    public static final Colour MISTYROSE = Colour.named("mistyrose");
    public static final Colour MISTYROSE1 = Colour.named("mistyrose1");
    public static final Colour MISTYROSE2 = Colour.named("mistyrose2");
    public static final Colour MISTYROSE3 = Colour.named("mistyrose3");
    public static final Colour MISTYROSE4 = Colour.named("mistyrose4");
    public static final Colour MOCCASIN = Colour.named("moccasin");
    public static final Colour NAVAJOWHITE = Colour.named("navajowhite");
    public static final Colour NAVAJOWHITE1 = Colour.named("navajowhite1");
    public static final Colour NAVAJOWHITE2 = Colour.named("navajowhite2");
    public static final Colour NAVAJOWHITE3 = Colour.named("navajowhite3");
    public static final Colour NAVAJOWHITE4 = Colour.named("navajowhite4");
    public static final Colour NAVY = Colour.named("navy");
    public static final Colour NAVYBLUE = Colour.named("navyblue");
    public static final Colour OLDLACE = Colour.named("oldlace");
    public static final Colour OLIVEDRAB = Colour.named("olivedrab");
    public static final Colour OLIVEDRAB1 = Colour.named("olivedrab1");
    public static final Colour OLIVEDRAB2 = Colour.named("olivedrab2");
    public static final Colour OLIVEDRAB3 = Colour.named("olivedrab3");
    public static final Colour OLIVEDRAB4 = Colour.named("olivedrab4");
    public static final Colour ORANGE = Colour.named("orange");
    public static final Colour ORANGE1 = Colour.named("orange1");
    public static final Colour ORANGE2 = Colour.named("orange2");
    public static final Colour ORANGE3 = Colour.named("orange3");
    public static final Colour ORANGE4 = Colour.named("orange4");
    public static final Colour ORANGERED = Colour.named("orangered");
    public static final Colour ORANGERED1 = Colour.named("orangered1");
    public static final Colour ORANGERED2 = Colour.named("orangered2");
    public static final Colour ORANGERED3 = Colour.named("orangered3");
    public static final Colour ORANGERED4 = Colour.named("orangered4");
    public static final Colour ORCHID = Colour.named("orchid");
    public static final Colour ORCHID1 = Colour.named("orchid1");
    public static final Colour ORCHID2 = Colour.named("orchid2");
    public static final Colour ORCHID3 = Colour.named("orchid3");
    public static final Colour ORCHID4 = Colour.named("orchid4");
    public static final Colour PALEGOLDENROD = Colour.named("palegoldenrod");
    public static final Colour PALEGREEN = Colour.named("palegreen");
    public static final Colour PALEGREEN1 = Colour.named("palegreen1");
    public static final Colour PALEGREEN2 = Colour.named("palegreen2");
    public static final Colour PALEGREEN3 = Colour.named("palegreen3");
    public static final Colour PALEGREEN4 = Colour.named("palegreen4");
    public static final Colour PALETURQUOISE = Colour.named("paleturquoise");
    public static final Colour PALETURQUOISE1 = Colour.named("paleturquoise1");
    public static final Colour PALETURQUOISE2 = Colour.named("paleturquoise2");
    public static final Colour PALETURQUOISE3 = Colour.named("paleturquoise3");
    public static final Colour PALETURQUOISE4 = Colour.named("paleturquoise4");
    public static final Colour PALEVIOLETRED = Colour.named("palevioletred");
    public static final Colour PALEVIOLETRED1 = Colour.named("palevioletred1");
    public static final Colour PALEVIOLETRED2 = Colour.named("palevioletred2");
    public static final Colour PALEVIOLETRED3 = Colour.named("palevioletred3");
    public static final Colour PALEVIOLETRED4 = Colour.named("palevioletred4");
    public static final Colour PAPAYAWHIP = Colour.named("papayawhip");
    public static final Colour PEACHPUFF = Colour.named("peachpuff");
    public static final Colour PEACHPUFF1 = Colour.named("peachpuff1");
    public static final Colour PEACHPUFF2 = Colour.named("peachpuff2");
    public static final Colour PEACHPUFF3 = Colour.named("peachpuff3");
    public static final Colour PEACHPUFF4 = Colour.named("peachpuff4");
    public static final Colour PERU = Colour.named("peru");
    public static final Colour PINK = Colour.named("pink");
    public static final Colour PINK1 = Colour.named("pink1");
    public static final Colour PINK2 = Colour.named("pink2");
    public static final Colour PINK3 = Colour.named("pink3");
    public static final Colour PINK4 = Colour.named("pink4");
    public static final Colour PLUM = Colour.named("plum");
    public static final Colour PLUM1 = Colour.named("plum1");
    public static final Colour PLUM2 = Colour.named("plum2");
    public static final Colour PLUM3 = Colour.named("plum3");
    public static final Colour PLUM4 = Colour.named("plum4");
    public static final Colour POWDERBLUE = Colour.named("powderblue");
    public static final Colour PURPLE = Colour.named("purple");
    public static final Colour PURPLE1 = Colour.named("purple1");
    public static final Colour PURPLE2 = Colour.named("purple2");
    public static final Colour PURPLE3 = Colour.named("purple3");
    public static final Colour PURPLE4 = Colour.named("purple4");
    public static final Colour RED = Colour.named("red");
    public static final Colour RED1 = Colour.named("red1");
    public static final Colour RED2 = Colour.named("red2");
    public static final Colour RED3 = Colour.named("red3");
    public static final Colour RED4 = Colour.named("red4");
    public static final Colour ROSYBROWN = Colour.named("rosybrown");
    public static final Colour ROSYBROWN1 = Colour.named("rosybrown1");
    public static final Colour ROSYBROWN2 = Colour.named("rosybrown2");
    public static final Colour ROSYBROWN3 = Colour.named("rosybrown3");
    public static final Colour ROSYBROWN4 = Colour.named("rosybrown4");
    public static final Colour ROYALBLUE = Colour.named("royalblue");
    public static final Colour ROYALBLUE1 = Colour.named("royalblue1");
    public static final Colour ROYALBLUE2 = Colour.named("royalblue2");
    public static final Colour ROYALBLUE3 = Colour.named("royalblue3");
    public static final Colour ROYALBLUE4 = Colour.named("royalblue4");
    public static final Colour SADDLEBROWN = Colour.named("saddlebrown");
    public static final Colour SALMON = Colour.named("salmon");
    public static final Colour SALMON1 = Colour.named("salmon1");
    public static final Colour SALMON2 = Colour.named("salmon2");
    public static final Colour SALMON3 = Colour.named("salmon3");
    public static final Colour SALMON4 = Colour.named("salmon4");
    public static final Colour SANDYBROWN = Colour.named("sandybrown");
    public static final Colour SEAGREEN = Colour.named("seagreen");
    public static final Colour SEAGREEN1 = Colour.named("seagreen1");
    public static final Colour SEAGREEN2 = Colour.named("seagreen2");
    public static final Colour SEAGREEN3 = Colour.named("seagreen3");
    public static final Colour SEAGREEN4 = Colour.named("seagreen4");
    public static final Colour SEASHELL = Colour.named("seashell");
    public static final Colour SEASHELL1 = Colour.named("seashell1");
    public static final Colour SEASHELL2 = Colour.named("seashell2");
    public static final Colour SEASHELL3 = Colour.named("seashell3");
    public static final Colour SEASHELL4 = Colour.named("seashell4");
    public static final Colour SIENNA = Colour.named("sienna");
    public static final Colour SIENNA1 = Colour.named("sienna1");
    public static final Colour SIENNA2 = Colour.named("sienna2");
    public static final Colour SIENNA3 = Colour.named("sienna3");
    public static final Colour SIENNA4 = Colour.named("sienna4");
    public static final Colour SKYBLUE = Colour.named("skyblue");
    public static final Colour SKYBLUE1 = Colour.named("skyblue1");
    public static final Colour SKYBLUE2 = Colour.named("skyblue2");
    public static final Colour SKYBLUE3 = Colour.named("skyblue3");
    public static final Colour SKYBLUE4 = Colour.named("skyblue4");
    public static final Colour SLATEBLUE = Colour.named("slateblue");
    public static final Colour SLATEBLUE1 = Colour.named("slateblue1");
    public static final Colour SLATEBLUE2 = Colour.named("slateblue2");
    public static final Colour SLATEBLUE3 = Colour.named("slateblue3");
    public static final Colour SLATEBLUE4 = Colour.named("slateblue4");
    public static final Colour SLATEGRAY = Colour.named("slategray");
    public static final Colour SLATEGRAY1 = Colour.named("slategray1");
    public static final Colour SLATEGRAY2 = Colour.named("slategray2");
    public static final Colour SLATEGRAY3 = Colour.named("slategray3");
    public static final Colour SLATEGRAY4 = Colour.named("slategray4");
    public static final Colour SLATEGREY = Colour.named("slategrey");
    public static final Colour SNOW = Colour.named("snow");
    public static final Colour SNOW1 = Colour.named("snow1");
    public static final Colour SNOW2 = Colour.named("snow2");
    public static final Colour SNOW3 = Colour.named("snow3");
    public static final Colour SNOW4 = Colour.named("snow4");
    public static final Colour SPRINGGREEN = Colour.named("springgreen");
    public static final Colour SPRINGGREEN1 = Colour.named("springgreen1");
    public static final Colour SPRINGGREEN2 = Colour.named("springgreen2");
    public static final Colour SPRINGGREEN3 = Colour.named("springgreen3");
    public static final Colour SPRINGGREEN4 = Colour.named("springgreen4");
    public static final Colour STEELBLUE = Colour.named("steelblue");
    public static final Colour STEELBLUE1 = Colour.named("steelblue1");
    public static final Colour STEELBLUE2 = Colour.named("steelblue2");
    public static final Colour STEELBLUE3 = Colour.named("steelblue3");
    public static final Colour STEELBLUE4 = Colour.named("steelblue4");
    public static final Colour TAN = Colour.named("tan");
    public static final Colour TAN1 = Colour.named("tan1");
    public static final Colour TAN2 = Colour.named("tan2");
    public static final Colour TAN3 = Colour.named("tan3");
    public static final Colour TAN4 = Colour.named("tan4");
    public static final Colour THISTLE = Colour.named("thistle");
    public static final Colour THISTLE1 = Colour.named("thistle1");
    public static final Colour THISTLE2 = Colour.named("thistle2");
    public static final Colour THISTLE3 = Colour.named("thistle3");
    public static final Colour THISTLE4 = Colour.named("thistle4");
    public static final Colour TOMATO = Colour.named("tomato");
    public static final Colour TOMATO1 = Colour.named("tomato1");
    public static final Colour TOMATO2 = Colour.named("tomato2");
    public static final Colour TOMATO3 = Colour.named("tomato3");
    public static final Colour TOMATO4 = Colour.named("tomato4");
    public static final Colour TRANSPARENT = Colour.named("transparent");
    public static final Colour TURQUOISE = Colour.named("turquoise");
    public static final Colour TURQUOISE1 = Colour.named("turquoise1");
    public static final Colour TURQUOISE2 = Colour.named("turquoise2");
    public static final Colour TURQUOISE3 = Colour.named("turquoise3");
    public static final Colour TURQUOISE4 = Colour.named("turquoise4");
    public static final Colour VIOLET = Colour.named("violet");
    public static final Colour VIOLETRED = Colour.named("violetred");
    public static final Colour VIOLETRED1 = Colour.named("violetred1");
    public static final Colour VIOLETRED2 = Colour.named("violetred2");
    public static final Colour VIOLETRED3 = Colour.named("violetred3");
    public static final Colour VIOLETRED4 = Colour.named("violetred4");
    public static final Colour WHEAT = Colour.named("wheat");
    public static final Colour WHEAT1 = Colour.named("wheat1");
    public static final Colour WHEAT2 = Colour.named("wheat2");
    public static final Colour WHEAT3 = Colour.named("wheat3");
    public static final Colour WHEAT4 = Colour.named("wheat4");
    public static final Colour WHITE = Colour.named("white");
    public static final Colour WHITESMOKE = Colour.named("whitesmoke");
    public static final Colour YELLOW = Colour.named("yellow");
    public static final Colour YELLOW1 = Colour.named("yellow1");
    public static final Colour YELLOW2 = Colour.named("yellow2");
    public static final Colour YELLOW3 = Colour.named("yellow3");
    public static final Colour YELLOW4 = Colour.named("yellow4");
    public static final Colour YELLOWGREEN = Colour.named("yellowgreen");

    private Colour(String key, String value) {
        super(key, value);
    }

    protected Colour(String value) {
        super("color", value);
    }

    public Colour fill() {
        return (Colour)this.key("fillcolor");
    }

    public Colour background() {
        return (Colour)this.key("bgcolor");
    }

    public Colour font() {
        return (Colour)this.key("fontcolor");
    }

    public Colour labelFont() {
        return (Colour)this.key("labelfontcolor");
    }

    public Colour gradient(Colour c) {
        return new Colour((String)this.value + ":" + (String)c.value);
    }

    public Colour gradient(Colour c, double at) {
        return new Colour((String)this.value + ":" + (String)c.value + ";" + at);
    }

    public Attrs angle(int angle) {
        return Attrs.attrs(this, new Attr<Integer>("gradientangle", angle));
    }

    public Attrs radial() {
        return this.radial(0);
    }

    public Attrs radial(int angle) {
        return Attrs.attrs(this, new Attr<Integer>("gradientangle", angle), Style.RADIAL);
    }

    public static Colour rgb(String rgb) {
        String val;
        String string = val = rgb.startsWith("#") ? rgb.substring(1) : rgb;
        if (val.length() != 6) {
            throw new IllegalArgumentException("Must have length 6");
        }
        return new Colour("#" + val);
    }

    public static Colour rgb(int rgb) {
        return Colour.rgb(Colour.hex(rgb >> 16) + Colour.hex(rgb >> 8) + Colour.hex(rgb));
    }

    public static Colour rgba(String rgba) {
        String val;
        String string = val = rgba.startsWith("#") ? rgba.substring(1) : rgba;
        if (val.length() != 8) {
            throw new IllegalArgumentException("Must have length 8");
        }
        return new Colour("#" + val);
    }

    public static Colour rgba(int rgba) {
        return Colour.rgba(Colour.hex(rgba >> 16) + Colour.hex(rgba >> 8) + Colour.hex(rgba) + Colour.hex(rgba >> 24));
    }

    private static String hex(int value) {
        String s = Integer.toHexString(value & 0xFF);
        return s.length() == 1 ? "0" + s : s;
    }

    public static Colour hsv(double h, double s, double v) {
        if (h < 0.0 || h > 1.0 || s < 0.0 || s > 1.0 || v < 0.0 || v > 1.0) {
            throw new IllegalArgumentException("Values must be 0<=value<=1");
        }
        return new Colour(h + " " + s + " " + v);
    }

    public static Colour named(String name) {
        return new Colour(name);
    }
}

